// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bootcamp_webapi;

namespace bootcamp_webapi.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20190808075732_InitialCreation")]
    partial class InitialCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("bootcamp_webapi.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Category");

                    b.Property<int>("Inventory");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Category = "Books",
                            Inventory = 5,
                            Name = "The Ultimate Guide To Budget Travel"
                        },
                        new
                        {
                            Id = 2L,
                            Category = "Sports",
                            Inventory = 4,
                            Name = "Upper Deck Baseball Set"
                        },
                        new
                        {
                            Id = 3L,
                            Category = "Groceries",
                            Inventory = 2,
                            Name = "Gatorade"
                        },
                        new
                        {
                            Id = 4L,
                            Category = "Electronics",
                            Inventory = 50,
                            Name = "Google Pixel 3"
                        },
                        new
                        {
                            Id = 5L,
                            Category = "Home and Garden",
                            Inventory = 20,
                            Name = "Kitchenette Stand Mixer"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
